---
- name: set timezone
  timezone:
    name: "{{ timezone }}"

- name: set locale
  locale_gen:
    name: zh_CN.UTF-8
    state: present

- name: set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname != 'localhost'